mari:
  parameter: sunrise time
  description: app for getting ${mari.parameter} parameter
  list: One,Two,Three
  dbValues: "{connection_string: 'http://db/slkm', user: 'mari', password: 431}"
db:
  dbValues: "{connection_string: 'http://test-db/slkm', user: 'mari', password: 431}"
  port: 5432
  status: true

management.endpoints.web.exposure.include: "*"
